apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeqr
    deploy: blue
  name: nodeqr
  namespace: blue
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: nodeqr
  type: ClusterIP